### ISSUE TITLE
Shape and color issues

### ISSUE THREAD

**Issue by plasticfist** [kinimesi/cytoscape-svg#8]
First, thank you for this, it looks like there are some style features that this (or the libraries it uses) fails to render as expected.   Is there a supported style reference list?   If there is I would evaluate changing my styles in order to get a good svg output.

I was surprised both by what it renders well, and just as surprised by the rest.

Here is an example cytoscape.js view
![image](https://user-images.githubusercontent.com/19381913/114916597-f996fb00-9df2-11eb-8498-51cbc89b1a14.png)

and the svg output
![image](https://user-images.githubusercontent.com/19381913/114916563-eedc6600-9df2-11eb-82bc-90a4a44c9846.png)

**Comment by plasticfist** [comment]
after several hours of trial and error, I can verify some styles that are problematic and need to be avoided...
- most of the rounded shapes, aka  `"shape" : "round-octagon"`, round-pentagon, barrel, etc
- the most problematic styling with a side effect, is if you use the edge style `"edge-text-rotation": "autorotate"`, while it DOES rotate the edge labels (see above) it also blacks out all the shapes...

**Comment by kinimesi** [comment]
Hi @plasticfist, the second problem you mentioned should be resolved in the unstable branch. Please see relevant issue #7 

The problem related to the shapes occurs with all rounded shapes. In the generated SVG, somehow the shape itself and its rounded corners are rotated and they don't align correctly. It needs further investigation.

**Comment by KonradHoeffner** [comment]
@kinimesi: I am using cytoscape-svg from npm where it is still only available as version 0.3.1, could you deploy the fixed version on npm?

**Comment by kinimesi** [comment]
I just published 0.4.0, try it out and let me know if it works, thanks.

**Comment by KonradHoeffner** [comment]
Yes it works perfectly, thanks!

**Comment by feichin-noreja** [comment]
> The problem related to the shapes occurs with all rounded shapes. In the generated SVG, somehow the shape itself and its rounded corners are rotated and they don't align correctly. It needs further investigation.

@kinimesi i still have the problem with the rounded corners. Any updates on this topic?
